### PR TITLE
Only forward matching HTTP methods

### PR DESCRIPTION
**Pull request by avdv**
Not the most elegant solution, but here goes...

### CODE REVIEW

**Comment by chrislusf** [comment]
Just saw this. Could you default the alternateMethods to empty string?

**Comment by avdv** [comment]
> Just saw this. Could you default the alternateMethods to empty string?

Sure, but you already merged... 🤔

I can create a follow up PR if you wish?!

**Comment by chrislusf** [comment]
found some bugs. fixed them. You can help to review my changes.

**Comment by avdv** [comment]
> found some bugs. fixed them. You can help to review my changes.

LGTM :+1:

**Pull request merged**
